/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:3538394f-2063-4803-bb3e-387750d823dc",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_vxq3WML7R",
  aws_user_pools_web_client_id: "4aufo24t5t69l0pe9ll7mq4sd2",
  oauth: {
    domain: "buddyup-dev.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "http://buddyup.netlify.app/login/",
    redirectSignOut: "http://buddyup.netlify.app/logout/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
